input_plugins: ["demo_input", "json_receiver"]
output_plugins: ["demo_output", "simple_html_viewer", "pico_display_output"]
core:
  buffer_size: 1000
  callsign: "M7FUS"
json_receiver:
  port: 9999
simple_html_viewer:
  port: 9998
serial_receiver:
  port: /dev/ttyUSB0
  baudrate: 115200
ssdv_serial_receiver:
  port: /dev/ttyUSB1
  baudrate: 115200
ozijson:
  host: 0.0.0.0
  port: 55673
sondehub:
  developer_mode: true
ssdv_to_disk:
  directory: /tmp/ssdv
demo_input:
  interval: 10  # seconds
pico_display_output:
  port: /dev/ttyACM1
  baudrate: 115200
